# Generated by Django 2.2.5 on 2020-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
