# Generated by Django 2.2.5 on 2020-01-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocSim',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('doc1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doc1', to='docsAnalysis.Document')),
                ('doc2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doc2', to='docsAnalysis.Document')),
            ],
        ),
    ]
