# Generated by Django 2.2.5 on 2020-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
                ('proj', models.CharField(max_length=50)),
            ],
        ),
    ]
