# Generated by Django 2.2.5 on 2020-01-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsim',
            name='value',
            field=models.FloatField(default=None),
        ),
    ]
