# Generated by Django 2.2.5 on 2020-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAnalysis', '0002_docsim_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='did',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
